
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
import firebaseModule as fb
import dieta



OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = "assets\\frame2"


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def cambioVentana(self, canvas):
    self.changeWindow(print)
    dieta.activate(self, canvas)
def activate(self, canvas):
    self.bagImage = PhotoImage(
        file = Path(__file__).parent/"assets\\fondo2.png"
    )       
    self.canvas.create_image(-180, -1250, anchor="nw", image=self.bagImage)
    self.image_image_1 = PhotoImage(
        file=relative_to_assets("image_1.png"))
    self.image_1 = canvas.create_image(
        188.0,
        54.0,
        image=self.image_image_1
    )

    userData = fb.read(self.db ,"infoUsuario", self.docID)
            
    canvas.create_text(
        197.5,
        50.0,
        anchor="center",
        text="Análisis nutricional ",
        fill="#FFFFFF",
        font=("Inter Extra Bold", 28 * -1)
    )

    infoGen = Text(
                bd=0,
                fg="#474747",
                highlightthickness=0,
                font=("Inter Extra Bold", 13 * -1),
                width = 40,
                height = 7,
                highlightbackground=None,
                bg=None,

            )
    infoGen.place(x = 55, y = 125)
    infoGen.insert(1.0, userData["informacion"].capitalize())
    infoGen["state"] = "disabled"
    
    canvas.create_text(
        187.0,
        492.0,
        anchor="center",
        text="\nSe recomienda mantener una actividad física constante y\n     equilibra entre ejercicios aeróbicos y anaeróbico.",
        fill="#474747",
        font=("Inter Extra Bold", 12 * -1)
    )

    canvas.create_text(
        187.5,
        301.0,
        anchor="center",
        text="IMC: 21.32\n*Se encuentra dentro del rango de peso "+str(userData["estado"])+".\n \n% de Grasa Corporal: "+str(userData["porcentajeGrasa"])+"%\n\n\n",
        fill="#474747",
        font=("Inter Extra Bold", 13 * -1)
    )

    canvas.create_text(
        187.5,
        113.0,
        anchor="center",
        text=str(userData["estado"].upper()),
        fill="#201375",
        font=("Inter Extra Bold", 13 * -1)
    )

    canvas.create_text(
        192.5,
        371.0,
        anchor="center",
        text="CALORÍAS",
        fill="#474747",
        font=("Inter Extra Bold", 13 * -1)
    )

    canvas.create_text(
        36.0,
        395.0,
        anchor="nw",
        text="Ingesta diaria:                                             "+str(userData["caloriasCal"])+"\nPara adelgazar:                                       "+str(userData["caloriasAdelgazar"])+"\nPara subir de peso:                                     "+str(userData["caloriasEngordar"]),
        fill="#474747",
        font=("Inter Extra Bold", 13 * -1)
    )

    self.image_image_2 = PhotoImage(
        file=relative_to_assets("image_2.png"))
    self.image_2 = canvas.create_image(
        187.0,
        354.0,
        image=self.image_image_2
    )

    self.image_image_3 = PhotoImage(
        file=relative_to_assets("image_3.png"))
    self.image_3 = canvas.create_image(
        187.0,
        463.0,
        image=self.image_image_3
    )

    self.image_image_4 = PhotoImage(
        file=relative_to_assets("image_4.png"))
    self.image_4 = canvas.create_image(
        118.0,
        604.0,
        image=self.image_image_4
    )

    self.button_image_1 = PhotoImage(
        file=relative_to_assets("button_1.png"))
    button_1 = Button(
        image=self.button_image_1,
        borderwidth=0,
        highlightthickness=0,
        command= lambda: cambioVentana(self, canvas),
        relief="flat",
        bg = "white"
    )
    button_1.place(
        x=173.0,
        y=590.0,
        width=142.0,
        height=36.0
    )

